import { StyleSheet, Platform } from "react-native";

// セリフ体フォント
const serifFont = Platform.OS === 'ios' ? 'Georgia' : 'serif';

const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  container: { flex: 1, backgroundColor: "#F5F5F5" },
  infoBanner: {
    marginTop: 8,
    marginHorizontal: 20,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 15,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: "#FFF",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  tabActive: { shadowOpacity: 0.12, shadowRadius: 8, elevation: 4 },
  tabText: { fontSize: 16, fontWeight: "600", letterSpacing: 0.3 },
  calendarIconButton: {
    position: "absolute",
    right: 20,
    padding: 8,
    zIndex: 10,
    backgroundColor: "#FFF",
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  calendarIcon: { fontSize: 24 },
  dateNavigation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 15,
    paddingHorizontal: 20,
  },
  navButton: { padding: 10 },
  navButtonText: { fontSize: 24, color: "#212121" },
  dateText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#212121",
    marginHorizontal: 4,
    minWidth: 120,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  dateLabelContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    marginTop: 4,
  },
  // Calendar modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 22, fontWeight: "700", color: "#212121" },
  modalClose: { fontSize: 28, color: "#757575" },
  monthSwitcher: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  calendarGrid: { paddingHorizontal: 20, paddingTop: 6 },
  weekdayRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 6,
  },
  weekdayText: {
    width: "14.28%",
    textAlign: "center",
    fontSize: 14,
    fontWeight: "600",
    color: "#757575",
  },
  calendarScroll: { marginBottom: 20 },
  calendarContent: { paddingHorizontal: 60, gap: 12 },
  calendarItem: {
    width: 70,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginHorizontal: 6,
    borderRadius: 16,
    backgroundColor: "#FFF",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  calendarItemSelected: { shadowOpacity: 0.15, shadowRadius: 8, elevation: 4 },
  calendarItemToday: { borderWidth: 2, borderColor: "#FF7043" },
  calendarDay: { width: "14.28%", height: 60, minHeight: 60 },
  calendarRingDay: { fontSize: 14, fontWeight: "800" },
  ringSmall: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  ringInner: { width: 28, height: 28, borderRadius: 14 },
  calendarDate: { fontSize: 12, fontWeight: "700", marginTop: 6 },
  calendarWeekday: { fontSize: 12, fontWeight: "600" },
  calendarCalories: { fontSize: 10, marginTop: 4 },
  calendarModalDayCell: {
    width: "14.28%",
    minHeight: 60,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    paddingVertical: 4,
  },
  calendarModalDayText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#212121",
    marginBottom: 2,
  },
  calendarModalSteps: { fontSize: 9, fontWeight: "600", marginBottom: 1 },
  calendarModalCalories: { fontSize: 8 },
  calendarWeek: { flexDirection: "row", marginBottom: 8 },
  // ページタイトル（Avenir Next太字）
  pageTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#00A896",
    textAlign: "center",
    marginBottom: 12,
    fontFamily: Platform.OS === "ios" ? "Avenir Next" : "Roboto",
  },
  // データページカード（ノート見開き用・紙テクスチャ風）
  dataPageCard: {
    borderRadius: 20,
    padding: 16,
    paddingBottom: 20,
    // 紙っぽいシャドウ（複数重ねてソフトに）
    shadowColor: '#8B8178',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    // 紙の縁取り風ボーダー
    borderWidth: 1,
    borderColor: '#E8E4DF',
    // 左側の綴じ穴風マーキング用スペース
    borderLeftWidth: 3,
    borderLeftColor: '#E0DCD6',
  },
  circleContainer: {
    alignItems: "center",
    marginTop: 4,
    marginBottom: 0,
    position: "relative",
  },
  circleBackground: {
    width: 220,
    height: 220,
    borderRadius: 110,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    // モダンな軽いシャドウ
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },

  circleCenter: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    width: 200,
    height: 200,
    top: 10,
    left: 10,
  },
  glowWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: -1, // 光を背面に押し込んでカレンダーなどを前面に
  },
  glow: {
    position: "absolute",
    shadowColor: "#FFE8D2",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 90,
    elevation: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#212121",
    marginLeft: 0,
    marginBottom: 4,
    letterSpacing: 0.5,
    fontFamily: serifFont,
  },
  chartSubtitle: {
    fontSize: 12,
    fontWeight: "500",
    color: "#9CA3AF",
    marginLeft: 0,
    marginBottom: 10,
  },
  percentText: { fontSize: 44, fontWeight: "800", letterSpacing: -1, fontFamily: serifFont },
  goalLabel: { fontSize: 13, fontWeight: "600", marginTop: 0 },
  progressSubtext: { fontSize: 12, fontWeight: "500", marginTop: 4 },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 14,
  },
  statCard: {
    flex: 1,
    borderRadius: 20,  // Slightly softer corners for paper feel
    padding: 16,
    marginHorizontal: 6,
    backgroundColor: "#FFF",
    // Paper card shadow
    shadowColor: "#1B1F23",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  statLabel: { fontSize: 12, fontWeight: "700", textAlign: "center" },
  statValue: {
    fontSize: 24,
    fontWeight: "800",
    marginTop: 2,
    textAlign: "center" },
  statSubtext: { fontSize: 12, marginTop: 4, textAlign: "center" },
  eventsCard: {
    borderRadius: 20,  // Paper card
    padding: 16,
    marginHorizontal: 20,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    // Paper shadow
    shadowColor: "#1B1F23",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 8,
  },
  eventsTitle: { fontSize: 16, fontWeight: "800", marginBottom: 8 },
  eventItem: { paddingVertical: 10, borderBottomWidth: 1 },
  eventTitle: { fontSize: 14, fontWeight: "700" },
  eventTime: { fontSize: 12 },
  moreEvents: { fontSize: 12, marginTop: 6 },
  noEventsText: { fontSize: 12, textAlign: "center" },
  // For compatibility with existing HomeScreen usage
  eventsContainer: {
    borderRadius: 12,
    padding: 15,
    marginHorizontal: 20,
    marginTop: 15,
    borderWidth: 1,
  },
  feedbackWrapper: {
    marginHorizontal: 20,
    marginBottom: 16,
    position: "relative",
  },
  feedbackPointerImage: { width: 54, height: 54 },
  feedbackPointerContainer: { position: "absolute", left: -12, top: -53 },
  feedbackCard: { borderRadius: 16, padding: 16, borderWidth: 1 },
  feedbackLabel: { fontSize: 12, fontWeight: "600", marginBottom: 6 },
  feedbackMessage: { fontSize: 16, fontWeight: "700", lineHeight: 22 },
  foodSection: { marginTop: 20, marginBottom: 30 },
  chartSection: { marginTop: 8, marginBottom: 0 },
  chartCard: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    borderStyle: 'dashed',
  },
  chartWithAxis: { flexDirection: "row", alignItems: "stretch" },
  yAxis: {
    width: 40,
    justifyContent: "space-between",
    paddingRight: 8,
    paddingTop: 10,
    paddingBottom: 25,
  },
  yAxisLabel: { fontSize: 11, color: "#9E9E9E", textAlign: "right" },
  chartArea: { flex: 1, paddingHorizontal: 4 },
  chart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: 200,
    paddingTop: 10,
    paddingBottom: 10,
  },
  barContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    height: "100%",
    paddingBottom: 30,
    position: "relative",
    marginHorizontal: 1,
  },
  barTouchable: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    width: "100%",
    position: "relative",
    overflow: "visible",
  },
  barWrapper: { width: "80%", flex: 1, justifyContent: "flex-end" },
  bar: {
    width: "100%",
    backgroundColor: "#FF8050",
    borderRadius: 4,
    minHeight: 2,
  },
  hourLabel: {
    fontSize: 10,
    color: "#9E9E9E",
    marginTop: 5,
    position: "absolute",
    bottom: -12,
    width: 34,
    textAlign: "center",
    writingDirection: "ltr",
  },
  hourlyDetailTooltipWrapper: {
    marginBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: "transparent",
  },
  hourlyDetailTooltip: {
    padding: 14,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  hourlyDetailTooltipTitle: {
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
  },
  hourlyDetailTooltipRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  hourlyDetailTooltipLabel: { fontSize: 12 },
  hourlyDetailTooltipValue: { fontSize: 13, fontWeight: "600" },
  
  // Date Navigation Styles (New)
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  dateNavButton: {
    padding: 10,
  },
  navButtonLeft: {
    // 矢印は日付の近くに
  },
  navButtonRight: {
    // 矢印は日付の近くに
  },
  dateNavArrow: {
    fontSize: 24,
    fontWeight: "600",
  },
  dateDisplay: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 140, // 日付幅を固定してセンタリング
    paddingHorizontal: 8,
  },
  disabledButton: {
    opacity: 0.3,
  },
});

export default styles;
